// <auto-generated />
using Academy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academy.Migrations
{
    [DbContext(typeof(AcademyContext))]
    partial class AcademyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Academy.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Programmers Group",
                            Name = "GR001"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Designers Group",
                            Name = "GR002"
                        });
                });

            modelBuilder.Entity("Academy.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            FirstName = "Denys",
                            GroupId = 1,
                            LastName = "Gladan"
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            FirstName = "Petro",
                            GroupId = 2,
                            LastName = "Sahaidachnyi"
                        },
                        new
                        {
                            Id = 3,
                            Age = 18,
                            FirstName = "Semen",
                            GroupId = 1,
                            LastName = "Kos"
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            FirstName = "Yurii",
                            GroupId = 1,
                            LastName = "Herych"
                        },
                        new
                        {
                            Id = 5,
                            Age = 15,
                            FirstName = "Yurii",
                            GroupId = 1,
                            LastName = "Korniichuk"
                        },
                        new
                        {
                            Id = 6,
                            Age = 37,
                            FirstName = "Symon",
                            GroupId = 2,
                            LastName = "Petliura"
                        },
                        new
                        {
                            Id = 7,
                            Age = 24,
                            FirstName = "Kostiantyn",
                            GroupId = 1,
                            LastName = "Palii"
                        },
                        new
                        {
                            Id = 8,
                            Age = 21,
                            FirstName = "Ivan",
                            GroupId = 2,
                            LastName = "Didenko"
                        },
                        new
                        {
                            Id = 9,
                            Age = 17,
                            FirstName = "Petro",
                            GroupId = 2,
                            LastName = "Ostapchenko"
                        },
                        new
                        {
                            Id = 10,
                            Age = 18,
                            FirstName = "Maxym",
                            GroupId = 2,
                            LastName = "Ukraiinec"
                        });
                });

            modelBuilder.Entity("Academy.Models.Student", b =>
                {
                    b.HasOne("Academy.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Academy.Models.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
